version: '3'  # version of compose format 

services:
  
  redis:
    image: redis:alpine

  drl-service:
    build: ./drl_service  # path is relative to docker-compose.yml location
    volumes:
      - ./drl_service:/app # mount point
    ports:
      - 5001:80  # host:container
    depends_on:
      - "redis"
 
